.DEFAULT_GOAL := ci-help

.PHONY: ci-help
ci-help:
	@printf '%s\n' 'Use an explicit ci-* target.'

include Makefile

.PHONY: ci-build-libroo ci-build-libroo-package ci-build-libroo-server ci-build-tools ci-build-native-packages ci-build-loom ci-build-lookup ci-build-proof ci-build-proofread ci-test-lang ci-test-package ci-test-server ci-test-proof ci-test-workbook ci-test-footsteps ci-test-rooc ci-test-roo-cli ci-test-loom-cli ci-test-lookup-cli ci-test-proofread

ci-build-libroo: configure
	cmake --build build --target roo_static roo_shared

ci-build-libroo-package:
	cmake --build build --target roo-package_static roo-package_shared

ci-build-libroo-server:
	cmake --build build --target roo-server_static roo-server_shared roo-server-exec

ci-build-tools:
	cmake --build build --target roo_cli rooc_cli

ci-build-native-packages:
	cmake --build build --target stage_native_packages

ci-build-loom:
	./build/rooc build $(NATIVE_PACKAGE_STAGE)/loom --build-dir $(CURDIR)/build/loom-build --name loom

ci-build-lookup:
	./build/rooc build $(NATIVE_PACKAGE_STAGE)/lookup --build-dir $(CURDIR)/build/lookup-build --name lookup

ci-build-proof:
	./build/rooc build $(NATIVE_PACKAGE_STAGE)/proof --build-dir $(CURDIR)/build/proof-build --name proof

ci-build-proofread:
	./build/rooc build $(NATIVE_PACKAGE_STAGE)/proofread --build-dir $(CURDIR)/build/proofread-build --name proofread

ci-test-lang:
	cmake --build build --target testroo
	./build/$(TEST_BINARY) --skip-benchmarks $(GTEST_FILTER_ARG)

ci-test-package:
	cmake --build build --target testpackage
	./build/$(PACKAGE_TEST_BINARY) $(GTEST_FILTER_ARG)

ci-test-server: configure-server-tests
	cmake --build build --target testserver
	./build/$(SERVER_TEST_BINARY) $(GTEST_FILTER_ARG)

ci-test-proof:
	cmake --build build --target testproof
	./build/$(PROOF_TEST_BINARY) $(GTEST_FILTER_ARG)

ci-test-workbook:
	cd $(NATIVE_PACKAGE_STAGE)/workbook/test && $(CURDIR)/build/roo proof

ci-test-footsteps:
	cd $(NATIVE_PACKAGE_STAGE)/footsteps/test && $(CURDIR)/build/roo proof

ci-test-rooc:
	cmake --build build --target testrooc
	./build/$(ROOC_TEST_BINARY) $(GTEST_FILTER_ARG)

ci-test-roo-cli:
	ROO_PACKAGE_STAGE_ROOT=$(NATIVE_PACKAGE_STAGE) sh $(CURDIR)/bin/roo/test/run-cli-tests.sh $(CURDIR)

ci-test-loom-cli:
	ROO_PACKAGE_STAGE_ROOT=$(NATIVE_PACKAGE_STAGE) sh $(CURDIR)/pkg/loom/test/run-cli-tests.sh $(CURDIR)

ci-test-lookup-cli:
	ROO_PACKAGE_STAGE_ROOT=$(NATIVE_PACKAGE_STAGE) sh $(CURDIR)/pkg/lookup/test/run-cli-tests.sh $(CURDIR)

ci-test-proofread:
	ctest --test-dir build -R proofread --output-on-failure
